name = "jingyue-nav"
pages_build_output_dir = "./public"
compatibility_date = "2026-04-26"

[vars]
WPS_WEBHOOK_JINGYUE = "https://www.kdocs.cn/api/v3/ide/file/corH6Pn7C9vm/script/V2-3VpBguvVTfZKpjuTNO5VE3/sync_task"
WPS_TOKEN_JINGYUE = "nT8dIhURZ1NlhWPAk7Q3u"
WPS_WEBHOOK_YUYAN = "https://www.kdocs.cn/api/v3/ide/file/ctSXn5QtcJcF/script/V2-6J8IjDAyuskT24h0VcppLj/sync_task"
WPS_TOKEN_YUYAN = "kn7wkfpT2G9VIfCIiM2Ou"

[env.preview.vars]
WPS_WEBHOOK_JINGYUE = "https://www.kdocs.cn/api/v3/ide/file/corH6Pn7C9vm/script/V2-3VpBguvVTfZKpjuTNO5VE3/sync_task"
WPS_TOKEN_JINGYUE = "nT8dIhURZ1NlhWPAk7Q3u"
WPS_WEBHOOK_YUYAN = "https://www.kdocs.cn/api/v3/ide/file/ctSXn5QtcJcF/script/V2-6J8IjDAyuskT24h0VcppLj/sync_task"
WPS_TOKEN_YUYAN = "kn7wkfpT2G9VIfCIiM2Ou"